site_name: Meatie
repo_url: https://github.com/pmateusz/meatie
repo_name: GitHub
theme: readthedocs

nav:
  - Home: index.md
  - Cookbook: cookbook.md

extra:
  repo_url: https://github.com/pmateusz/meatie/tree/master/

plugins:
  - search
  - macros
  - mkdocstrings:
      handlers:
        python:
          options:
            allow_inspection: true
            find_stubs_package: true
            show_source: true
            show_source_type: true
            show_source_link: true
            show_source_full_path: true
