site_name: Meatie
repo_url: https://github.com/pmateusz/meatie
repo_name: GitHub
theme:
  name: material

nav:
  - Home: index.md
  - Cookbook: cookbook.md
  - Reference: references.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
