site_name: Meatie
theme: readthedocs
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            allow_inspection: true
            find_stubs_package: true
            show_source: true
            show_source_type: true
            show_source_link: true
            show_source_full_path: true
