site_name: Meatie
repo_url: https://github.com/pmateusz/meatie
repo_name: GitHub
theme:
  name: material
  features:
    - content.code.copy

nav:
  - Home: index.md
  - Cookbook: cookbook.md
  - Tutorials:
    - Getting Started: tutorials/getting_started.md
    - Authentication: tutorials/authentication.md
    - Rate Limiting: tutorials/rate_limiter.md
    - Caching: tutorials/caching.md
  - Reference: references.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
