name: Lint
on:
  workflow_call:
    inputs:
      python_version:
        type: string
        description: 'Python version'
        required: true
  workflow_dispatch:
    inputs:
      python_version:
        type: string
        description: 'Python version'
        required: true
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      branch: ${{ github.head_ref || github.ref_name }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --no-default-groups --group dev --python ${{ inputs.python_version || github.event.inputs.python_version }}

      - name: Cache pre-commit hooks
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        run: uv run pre-commit run --all
        continue-on-error: true

      - name: Run mypy
        run: uv run mypy src
        continue-on-error: true

      - name: Check for linting errors
        if: failure()
        run: |
          echo "Linting checks failed. Please review the output above."
          exit 1
