name: Release Package
on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch: {}
permissions:
  id-token: write
jobs:
  ci:
    uses: ./.github/workflows/ci.yaml

  publish:
    needs: [ci]
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install build tools
        run: uv pip install hatchling
      - name: Set project version
        run: uv run hatchling version $(echo -n ${{ github.ref_name }} | grep -oP '\d+.\d+.\d+')
      - name: Build package
        run: uv build
      - name: Verify wheel package
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install dist/meatie-*.whl
          uv pip install -r pyproject.toml --extra httpx --extra requests --extra aiohttp
          python -c "import meatie; import meatie_httpx; import meatie_requests; import meatie_aiohttp"
      - name: Verify tar.gz package
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install dist/meatie-*.tar.gz
          uv pip install -r pyproject.toml --extra httpx --extra requests --extra aiohttp
          python -c "import meatie; import meatie_httpx; import meatie_requests; import meatie_aiohttp"
      - name: Publish package
        run: uv publish --trusted-publishing always
