name: Test
on:
  workflow_call:
    inputs:
      python_version:
        type: string
        description: 'Python version'
        required: true
      upload_coverage:
        type: boolean
        description: 'Upload coverage'
        default: false
  workflow_dispatch:
    inputs:
      python_version:
        type: string
        description: 'Python version'
        required: true
      upload_coverage:
        type: boolean
        description: 'Upload coverage'
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      branch: ${{ github.head_ref || github.ref_name }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --no-default-groups --group test --group all-backends --python ${{ inputs.python_version || github.event.inputs.python_version }}

      - name: Run tests
        run: uv run pytest

      - name: Upload coverage reports to Codecov
        if: ${{ inputs.upload_coverage || github.event.inputs.upload_coverage }}
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          file: coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
