name: Test Matrix
on: [ workflow_dispatch ]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      branch: ${{ github.head_ref || github.ref_name }}
    strategy:
      matrix:
        python_version: ['3.9', '3.10', '3.11', '3.12', '3.13']
        dependencies: ['aiohttp', 'requests', 'httpx', 'pydantic-v2']
        include:
          - python_version: '3.12'
            dependencies: ['aiohttp', 'pydantic-v2']
          - python_version: '3.12'
            dependencies: ['requests', 'pydantic-v2']
          - python_version: '3.12'
            dependencies: ['httpx', 'pydantic-v2']
          - python_version: '3.12'
            dependencies: ['aiohttp','requests','httpx', 'pydantic-v1']
          - python_version: '3.12'
            dependencies: ['aiohttp','requests','httpx']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync --no-install-project --group=test

      - name: Install aiohttp
        if: ${{ contains(matrix.dependencies, 'aiohttp') }}
        run: uv pip install -r pyproject.toml --extra=aiohttp

      - name: Install requests
        if: ${{ contains(matrix.dependencies, 'requests') }}
        run: uv pip install -r pyproject.toml --extra=requests

      - name: Install httpx
        if: ${{ contains(matrix.dependencies, 'httpx') }}
        run: uv pip install -r pyproject.toml --extra=httpx

      - name: Install pydantic v1
        if: ${{ contains(matrix.dependencies, 'pydantic-v1') }}
        run: uv pip install pydantic===1.10.13

      - name: Install pydantic v2
        if: ${{ contains(matrix.dependencies, 'pydantic-v2') }}
        run: uv pip install -r pyproject.toml --extra=pydantic

      - name: Run pytest
        run: uv run pytest
