name: Test
on:
  workflow_call:
    inputs:
      python_version:
        type: string
        description: 'Python version'
        required: true
  workflow_dispatch:
    inputs:
      python_version:
        type: string
        description: 'Python version'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      branch: ${{ github.head_ref || github.ref_name }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install dependencies
        run: uv sync --no-install-project --all-extras

      - name: Run tests
        run: uv run pytest
